-- backend/schema.sql
-- Run this script in the Supabase SQL Editor to create all necessary tables
-- and grant appropriate permissions for the API.

-- 1. Faculty Table
CREATE TABLE IF NOT EXISTS faculty (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT NOT NULL,
    subjects TEXT[] NOT NULL DEFAULT '{}',
    available_from TEXT NOT NULL DEFAULT '09:00',
    available_to TEXT NOT NULL DEFAULT '17:00',
    preferred_time TEXT NOT NULL DEFAULT 'Any',
    max_load INT NOT NULL DEFAULT 20,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Rooms Table
CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('Classroom', 'Lab')),
    capacity INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Subjects Table
CREATE TABLE IF NOT EXISTS subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT,
    lectures_per_week INT NOT NULL DEFAULT 3,
    labs_per_week INT NOT NULL DEFAULT 0,
    requires_lab BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Sections Table
CREATE TABLE IF NOT EXISTS sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    strength INT NOT NULL DEFAULT 60,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Timetable Table
CREATE TABLE IF NOT EXISTS timetable (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day TEXT NOT NULL,
    day_order INT NOT NULL,
    period TEXT NOT NULL,
    is_morning BOOLEAN NOT NULL DEFAULT FALSE,
    section TEXT NOT NULL,
    subject TEXT NOT NULL,
    faculty_code TEXT NOT NULL,
    faculty_name TEXT,
    room TEXT NOT NULL,
    is_lab BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Disable Row Level Security (RLS) so the college app can read/write directly
ALTER TABLE faculty DISABLE ROW LEVEL SECURITY;
ALTER TABLE rooms DISABLE ROW LEVEL SECURITY;
ALTER TABLE subjects DISABLE ROW LEVEL SECURITY;
ALTER TABLE sections DISABLE ROW LEVEL SECURITY;
ALTER TABLE timetable DISABLE ROW LEVEL SECURITY;

-- 7. Grant full access to anon and authenticated roles
GRANT ALL ON TABLE faculty TO anon, authenticated, service_role;
GRANT ALL ON TABLE rooms TO anon, authenticated, service_role;
GRANT ALL ON TABLE subjects TO anon, authenticated, service_role;
GRANT ALL ON TABLE sections TO anon, authenticated, service_role;
GRANT ALL ON TABLE timetable TO anon, authenticated, service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
